const profile = {
  name: "Hoda Ebrahimi",
  role: "Ph.D. Student in Computing Science",
  about:
    "I'm a PhD student in Computing Science at the University of Alberta. I work on training segmentation models under heterogeneous supervision — combining a small set of clean expert labels with much larger sets of noisy pseudo-labels generated by foundation models. The application area is intestinal tract segmentation in IBD patients, which means I also spend time building the cloud-based annotation tools clinicians use to refine and validate the data.",
  skillCategories: [
    {
      name: "Programming",
      items: ["Python (primary)", "MATLAB", "C", "VHDL", "Assembly", "Java*", "Bash"],
    },
    {
      name: "ML & Data",
      items: [
        "PyTorch",
        "scikit-learn",
        "NumPy",
        "Pandas",
        "SciPy",
        "OpenCV",
        "Matplotlib",
        "Jupyter",
      ],
    },
    {
      name: "Methods",
      items: [
        "Deep learning (CNNs, Transformers, U-Net variants)",
        "Ensemble methods",
        "Transfer learning",
        "Uncertainty quantification",
        "Semi-supervised learning",
        "Knowledge distillation",
        "GANs",
      ],
    },
    {
      name: "Medical Imaging",
      items: [
        "3D Slicer",
        "ITK-SNAP",
        "SimpleITK",
        "nnUNet",
        "TotalSegmentator",
        "Vista3D",
        "MedSAM",
      ],
    },
    {
      name: "Infrastructure",
      items: [
        "AWS (AppStream, S3)",
        "Docker",
        "Git/GitHub",
        "SLURM/HPC",
        "Distributed training (DDP)",
      ],
    },
    {
      name: "Hardware/EDA",
      items: [
        "Altium Designer",
        "OrCAD PSpice",
        "Proteus Design Suite",
        "Xilinx ISE/Vivado",
        "ADS",
      ],
    },
    {
      name: "IDEs & Tools",
      items: ["PyCharm", "VS Code", "Google Colab", "LaTeX", "Microsoft Office"],
    },
    {
      name: "OS",
      items: ["Windows", "Linux"],
    },
  ],
  education: [
    {
      title: "University of Alberta, Edmonton, AB",
      subtitle: "Ph.D. in Computing Science (GPA: 4.0/4.0)",
      date: "Sep. 2023 – Present",
      details:
        "Supervisors: Dr. J. Ross Mitchell and Dr. Randy Goebel. NSERC From Data To Decision (FD2D) Scholarship (2025–2027).",
    },
    {
      title: "Iran University of Science and Technology, Tehran, Iran",
      subtitle:
        "M.Sc. in Electrical Engineering – Digital Electronic Systems (GPA: 18.31/20.0 · 3.77/4.0)",
      date: "Sep. 2019 – May 2022",
      details:
        "Thesis: Action Recognition in Still Images using Attention Mechanism. Supervisor: Dr. Shahriar B. Shokouhi.",
    },
    {
      title: "K. N. Toosi University of Technology, Tehran, Iran",
      subtitle:
        "B.Sc. in Electrical Engineering – Electronics (GPA: 18.50/20.0 · 3.80/4.0)",
      date: "Sep. 2015 – Sep. 2019",
      details:
        "Thesis: Design and Construction of Fuel Injection and Ignition System. Supervisor: Dr. Amir Mousavi Nia. Award: Distinguished student commendation letter from the president of KNTU.",
    },
  ],
  research: [
    {
      title: "Medical Imaging Research Lab, University of Alberta",
      subtitle: "PhD Research Assistant",
      date: "Sep. 2023 – Present",
      bullets: [
        "Medical Image Segmentation & Validation: IBD segmentation in CT enterography, uncertainty quantification, human-in-the-loop annotation workflows.",
        "Image Processing & Visualization: 3D Slicer, ITK-SNAP for medical image annotation and visualization, SimpleITK for preprocessing pipelines.",
        "Cloud Deployment: AWS AppStream for deploying annotation applications, multi-user workflows, S3 integration.",
        "Deep Learning: nnUNet, TotalSegmentator, Vista3D, MedSAM for medical image segmentation; semi-supervised learning with custom dual-loss methods.",
      ],
    },
    {
      title: "Computer Vision Lab, IUST",
      subtitle: "Research Assistant",
      date: "Sep. 2019 – May 2022",
      bullets: [
        "Advanced Machine Vision & Deep Learning: Image Classification (Transformers, CNNs), Object Detection, Image Segmentation, Pose Estimation, Human Action Recognition, Gait Recognition, Knowledge Distillation, Ensemble Learning, Self-Supervised Learning.",
        "Medical Image Processing: Breast Tumor Classification in MRI.",
        "Technical Skills: PyTorch (MLP, CNN, RNN, GAN, ViT), Image Processing with Python.",
      ],
    },
    {
      title: "ICD Lab, KNTU",
      subtitle: "Research Assistant",
      date: "Jun. – Sep. 2019",
      bullets: [
        "Micro-Controller Programming: Implemented ECU Simulator for Fuel Injection and Ignition using AVR.",
        "Circuit Design: Designed ECU Simulator using Altium Designer to interface with Motor Simulator.",
      ],
    },
  ],
  phdProjects: [
    {
      title: "Semi-Supervised Segmentation of Intestinal Tract on CT",
      subtitle: "PhD Research",
      date: "Sep. 2024 – Present",
      bullets: [
        "Designed and ran experiments comparing supervised baselines, Mean Teacher, and a custom dual-loss method on ~5,000 abdominal CT scans, using Dice as the primary evaluation metric across three anatomical classes.",
        "Built a custom preprocessing pipeline in nnUNet v2 to handle overlapping multi-class soft labels, including Blosc2 storage and DDP-aware batch composition.",
        "Diagnosed counterintuitive empirical results (Dice decreasing with more labeled data) by tracing them to label-noise and calibration issues in the source dataset; switched evaluation to an external test set with expert annotations to validate the finding.",
        "Communicate progress weekly to two supervisors and clinical collaborators, including an 8-minute talk to non-technical judges at GI Research Day.",
      ],
    },
    {
      title: "Cloud-Based Medical Image Annotation Platform",
      subtitle: "PhD Research",
      date: "Winter 2024 – Fall 2025",
      bullets: [
        "Deployed a 3D Slicer-based annotation application on AWS AppStream for five physician reviewers, with S3-backed storage, user assignment scripts, and synchronized data flow between local and cloud.",
        "Built a DICOM-metadata pipeline to identify CT enterography studies inside a hospital archive of 10K+ scans, replacing a previously manual curation step.",
        "Gathered requirements from physician users directly and iterated on the interface and workflow based on their feedback.",
      ],
    },
    {
      title: "Foundation-Model Ensemble for Medical Image Pseudo-Labels",
      subtitle: "PhD Research",
      date: "2024 – Present",
      bullets: [
        "Ran inference with three pretrained foundation models (TotalSegmentator, Vista3D, MedSAM) on ~10K CT scans and combined their outputs into ensemble pseudo-labels using a probabilistic fusion method.",
        "Implemented a Bernoulli-variance uncertainty score to rank cases by predicted difficulty, used to prioritize which scans get sent to clinicians for manual review.",
      ],
    },
    {
      title: "Medical Image Comparison Tool",
      subtitle: "PhD Research",
      date: "Winter 2026",
      bullets: [
        "Developed a cloud-based synchronized dual ITK-SNAP window system for blinded physician evaluation of human vs. AI segmentations across 4 brain lesion types.",
        "Implemented an automated case loading and configuration pipeline, eliminating manual setup and enabling physicians to evaluate segmentation quality without technical overhead.",
      ],
    },
  ],
  personalProjects: [
    {
      title: "Semantic Image Search Engine",
      subtitle: "Personal Project",
      date: "2025",
      github: "https://github.com/hodaebrahimi/clip-image-search",
      bullets: [
        "Built a semantic image retrieval system using OpenAI's CLIP to support both text-to-image and image-to-image search, leveraging CLIP's joint vision–language embedding space.",
        "Implemented a FAISS IndexFlatIP vector index over L2-normalized embeddings for efficient cosine-similarity search across the indexed image set.",
        "Wrapped the end-to-end pipeline (dataset download → batch embedding generation → index building → query) in a Gradio web UI with separate text and image query tabs.",
      ],
    },
    {
      title: "Real-Time Object Detection & Tracking Pipeline",
      subtitle: "Personal Project",
      date: "2025",
      github: "https://github.com/hodaebrahimi/realtime-detection-tracker",
      bullets: [
        "Built a video analytics pipeline combining YOLOv8 detection with ByteTrack multi-object tracking (via the Supervision library), producing annotated frames with bounding boxes, track IDs, and an on-frame FPS overlay.",
        "Implemented CLI entry points for video-file processing and live webcam capture, plus a Gradio web UI for video upload with configurable model size (nano/small/medium) and detection confidence threshold.",
        "Organized the codebase into separable modules (detector, tracker, annotator, pipeline, runner) with unit tests covering each stage; supports the COCO-80 class set.",
      ],
    },
  ],
  academicProjects: [
    {
      title: "Action Recognition in Still Images using Attention Mechanism",
      subtitle: "M.Sc. Thesis | Skills: PyTorch, OpenCV, NumPy",
      date: "Sep. 2021 – May 2022",
      bullets: [
        "Trained Vision Transformer (ViT) and ResNeXt50 models on the Stanford40 dataset, a benchmark dataset for action recognition tasks.",
        "Employed ensemble learning to combine ViT and ResNeXt50, leveraging global relations captured by multi-head attention in ViT and local features learned by CNNs in ResNeXt50.",
        "Incorporated attention mechanisms to enhance the models' capability to focus on relevant regions of the input images, improving action recognition accuracy.",
        "Conducted comprehensive analysis and evaluation, achieving 94.98% mAP (~1 point above the CNN-only baseline).",
      ],
    },
    {
      title: "Breast Tumor Classification on Duke Dataset Using Ensemble Learning",
      subtitle: "Skills: PyTorch, OpenCV, NumPy",
      date: "Mar. – May 2022",
      bullets: [
        "Trained CNNs with ImageNet pre-trained weights, enhanced models by adding CBAM modules to the last layer, and employed ensemble learning with four top models on the Duke breast cancer MRI dataset, achieving 92.43% accuracy.",
        "Used dataset annotations to locate tumor-containing slices, reducing MRI dimensionality from 4D to 2D RGB images to leverage pretrained models and fit GPU memory constraints (Google Colab Tesla P100, 16GB).",
      ],
    },
    {
      title:
        "End-to-End 3D Human Pose Estimation in Still Images using a 2D-to-3D Lifting Model",
      subtitle: "Skills: PyTorch",
      date: "Fall 2023",
      bullets: [
        "Implemented a Transformer-based 2D pose estimator (TransPose) combined with a 2D-to-3D lifting MLP on the 3D Poses in the Wild dataset, identifying limitations of frozen backbone architecture for this challenging dataset.",
      ],
    },
    {
      title:
        "Applying End-to-End Edge-Enhancement GAN and Object Detector on Bosch Small Traffic Lights",
      subtitle: "Skills: PyTorch",
      date: "Fall 2020",
      bullets: [
        "Applied an object detection network combined with a super-resolution GAN for edge enhancement on the Bosch Small Traffic Lights dataset, aimed at improving accuracy and robustness of small traffic light detection.",
      ],
    },
    {
      title: "Face Generation using GAN on CelebFaces Dataset",
      subtitle: "Skills: PyTorch, OpenCV, NumPy",
      date: "Fall 2020",
      bullets: [],
    },
    {
      title:
        "Forecasting Geomagnetic Activity Indices (Kp, AE, Dst) using MLP and RBF Networks",
      subtitle: "Skills: PyTorch, NumPy, Pandas",
      date: "Fall 2020",
      bullets: [],
    },
    {
      title: "Design and Construction of Fuel Injection and Ignition System",
      subtitle: "B.Sc. Thesis | Skills: C, Code Vision, Altium Designer",
      date: "Mar. – Sep. 2019",
      bullets: [
        "Developed a control system using AVR microcontroller technology to regulate fuel injection and ignition timing in a single-cylinder internal combustion engine.",
        "Engineered signal processing algorithms to adjust air–fuel mixture for optimal engine performance and efficiency.",
        "Implemented precise timing mechanisms to deliver ignition sparks at optimal intervals, ensuring smooth engine operation.",
      ],
    },
    {
      title: "Traffic Light Control System with AVR Micro-Controller",
      subtitle: "Skills: C, Code Vision",
      date: "Fall 2017",
      bullets: [
        "Developed a traffic light control system using an AVR micro-controller programmed in C within Code Vision. Implemented program logic to simulate traffic light operation at an intersection, including red/yellow/green signal phases and pedestrian crossing requests.",
      ],
    },
    {
      title: "Implementation and Testing of AES Cipher Encryption Using FPGA",
      subtitle: "Skills: VHDL, Xilinx Vivado",
      date: "Winter 2018",
      bullets: [
        "Designed, implemented, and tested a hardware-accelerated AES cipher encryption algorithm using FPGA technology, leveraging dedicated hardware for cryptographic computations to enhance encryption performance and security.",
      ],
    },
    {
      title: "FPGA-based Keyboard Input and Graphical LCD Display System",
      subtitle: "Skills: VHDL, Xilinx Vivado, Graphical LCD",
      date: "Winter 2018",
      bullets: [
        "Developed a custom input and display system using an FPGA board, facilitating keyboard input and real-time display on a graphical LCD; demonstrated proficiency in FPGA programming, digital design, and hardware interfacing for embedded systems.",
      ],
    },
  ],
  teaching: [
    {
      title: "Teaching Assistant, University of Alberta",
      subtitle: "CMPUT 174 – Introduction to Foundations of Computation I (Python)",
      date: "Fall 2023, Fall 2024",
      detail: "Lab instruction, office hours, assignment grading.",
    },
    {
      title: "Teaching Assistant, University of Alberta",
      subtitle: "CMPUT 101 – Introduction to Computing",
      date: "Winter 2024, Winter 2025",
      detail: "Lab instruction, office hours, grading, exam supervision.",
    },
  ],
  industry: [
    {
      title: "Electronic Research & Production Co. TAKTA",
      subtitle: "R&D Intern",
      date: "Jun. – Aug. 2018",
      bullets: [
        "FPGA programming for receiver controllers and Surface Mount Device (SMD) soldering in an R&D environment.",
        "Demonstrated versatility in hardware development and assembly across multiple project areas.",
      ],
    },
  ],
  publications: [
    'H. Ebrahimi, et al. "Cloud-Based Medical Image Annotation Platform for Multi-User Workflows." Technical Letter — In Preparation.',
    'H. Ebrahimi, et al. "Foundation Models for Intestinal Tract Segmentation in IBD Patients." In Preparation (target: MICCAI 2026 workshop).',
  ],
  awards: [
    "NSERC From Data To Decision (FD2D) Scholarship — two years full funding (Fall 2025 – Spring 2027).",
    "Ranked 4th among graduating Electrical Engineering-Electronics students and selected as an Exceptionally Talented Student (KNTU, 2018).",
  ],
  certificates: [
    "AVR Micro-Controller Programming — IEEE Student Branch, K. N. Toosi University of Technology (Feb. 2018).",
    "MATLAB — Tehran Institute of Technology (Aug. 2016).",
  ],
  courses: {
    graduate: [
      "Machine Learning: 19.0/20.0",
      "Machine Vision: 19.5/20.0",
      "Advanced Micro-Processor: 18.8/20.0",
      "Advanced Computer Architecture: 18.5/20.0",
      "Earth Observation (U of A): 4.0/4.0",
    ],
    undergraduate: [
      "Engineering Mathematics: 19.25/20.0",
      "Engineering Probability: 19.7/20.0",
      "Digital Systems Design: 19.5/20.0",
      "Digital Signal Processing: 17.3/20.0",
      "Signals and Systems: 19.5/20.0",
      "Digital Systems Lab I: 20.0/20.0",
      "Digital Systems II: 20.0/20.0",
    ],
  },
  additional: [
    "Languages: English — TOEFL iBT 112/120 (R:29, L:29, S:27, W:27), Nov. 2022; German — B1 Intermediate.",
    "Work Authorization: Eligible to work in Canada (full-time, no restrictions) until May 30, 2027.",
  ],
  references: [
    "Dr. J. Ross Mitchell — Professor, Dept. of Medicine & Dentistry, University of Alberta. jmitche2@ualberta.ca",
    "Dr. Shahriar Baradaran Shokouhi — Associate Professor, Dept. of Electrical Engineering, IUST. bshokouhi@iust.ac.ir",
    "Dr. Amir Mousavi Nia — Assistant Professor, Dept. of Computer Engineering, KNTU. moosavie@kntu.ac.ir",
    "Dr. Hossein Shamsi — Associate Professor, Dept. of Electrical Engineering, KNTU. shamsi@eetd.kntu.ac.ir",
  ],
  researchInterests: [
    "Medical Image Analysis",
    "Deep Learning for Healthcare",
    "Computer Vision / Image Processing",
    "Human-in-the-Loop Systems",
    "Foundation Models",
    "Image Segmentation",
    "Generative Models",
  ],
  contactText:
    "Open to research collaborations, internships, and AI-for-healthcare opportunities.",
  contacts: [
    { label: "Email", href: "mailto:hodaebrahimi75@gmail.com" },
    { label: "Phone", href: "tel:+17807162521" },
    { label: "Lab Website", href: "https://sites.ualberta.ca/~jmitche2/" },
    {
      label: "LinkedIn",
      href: "https://www.linkedin.com/in/hoda-ebrahimi-88a49a239/",
    },
    { label: "GitHub", href: "https://github.com/hodaebrahimi" },
  ],
};

const setText = (id, value) => {
  const node = document.getElementById(id);
  if (node && typeof value === "string") node.textContent = value;
};

const createMeta = (subtitle, date) => {
  if (!subtitle && !date) return "";
  if (subtitle && date) return `${subtitle} | ${date}`;
  return subtitle || date;
};

const fillList = (id, items) => {
  const node = document.getElementById(id);
  if (!node) return;
  items.forEach((item) => {
    const li = document.createElement("li");
    li.textContent = item;
    node.appendChild(li);
  });
};

const renderBullets = (bullets) =>
  bullets && bullets.length
    ? `<ul class="card-bullets">${bullets.map((b) => `<li>${b}</li>`).join("")}</ul>`
    : "";

const renderWorkCards = (nodeId, items) => {
  const node = document.getElementById(nodeId);
  if (!node) return;
  items.forEach((item) => {
    const card = document.createElement("article");
    card.className = "work-card";
    const meta = createMeta(item.subtitle, item.date);
    const githubLink = item.github
      ? `<a class="work-link" href="${item.github}" target="_blank" rel="noreferrer">GitHub →</a>`
      : "";
    card.innerHTML = `<h3>${item.title}</h3><p class="item-meta">${meta}</p>${renderBullets(item.bullets)}${githubLink}`;
    node.appendChild(card);
  });
};

setText("hero-role", profile.role);
setText("hero-name", `Hi, I'm ${profile.name}.`);
setText("about-text", profile.about);
setText("contact-text", profile.contactText);

document.title = `${profile.name} | Background & Work`;
document.getElementById("year").textContent = new Date().getFullYear();

// Skills
const skillsNode = document.getElementById("skills-list");
profile.skillCategories.forEach(({ name, items }) => {
  const row = document.createElement("div");
  row.className = "skill-category";

  const label = document.createElement("span");
  label.className = "skill-category-name";
  label.textContent = name;

  const chips = document.createElement("div");
  chips.className = "skill-chips";
  items.forEach((item) => {
    const chip = document.createElement("span");
    chip.className = "skill-chip";
    chip.textContent = item;
    chips.appendChild(chip);
  });

  row.appendChild(label);
  row.appendChild(chips);
  skillsNode.appendChild(row);
});

const interestsNode = document.createElement("div");
interestsNode.className = "interests-row";
const interestsTitle = document.createElement("h3");
interestsTitle.textContent = "Research Interests";
const interestsText = document.createElement("p");
interestsText.textContent = profile.researchInterests.join(" • ");
interestsNode.appendChild(interestsTitle);
interestsNode.appendChild(interestsText);
skillsNode.parentElement.appendChild(interestsNode);

// Education
const educationNode = document.getElementById("education-list");
profile.education.forEach((item) => {
  const block = document.createElement("article");
  block.className = "timeline-item";
  const meta = createMeta(item.subtitle, item.date);
  block.innerHTML = `<h3>${item.title}</h3><p>${meta}</p><p>${item.details || ""}</p>`;
  educationNode.appendChild(block);
});

// Research Experience (lab-level)
renderWorkCards("research-list", profile.research);

// PhD Research Projects
renderWorkCards("phd-projects-list", profile.phdProjects);

// Personal Projects
renderWorkCards("personal-projects-list", profile.personalProjects);

// Academic Projects
renderWorkCards("academic-projects-list", profile.academicProjects);

// Teaching
const teachingNode = document.getElementById("teaching-list");
profile.teaching.forEach((item) => {
  const block = document.createElement("article");
  block.className = "timeline-item";
  const meta = createMeta(item.subtitle, item.date);
  block.innerHTML = `<h3>${item.title}</h3><p>${meta}</p>${item.detail ? `<p>${item.detail}</p>` : ""}`;
  teachingNode.appendChild(block);
});

// Industrial Experience
renderWorkCards("industry-list", profile.industry);

// Awards section lists
fillList("awards-list", profile.awards);
fillList("certificates-list", profile.certificates);
fillList("additional-list", profile.additional);

// Selected Courses (two-column)
const coursesContainer = document.getElementById("courses-container");
if (coursesContainer) {
  ["graduate", "undergraduate"].forEach((level) => {
    const col = document.createElement("div");
    col.className = "courses-column";
    const heading = document.createElement("h4");
    heading.textContent = level.charAt(0).toUpperCase() + level.slice(1);
    const list = document.createElement("ul");
    profile.courses[level].forEach((c) => {
      const li = document.createElement("li");
      li.textContent = c;
      list.appendChild(li);
    });
    col.appendChild(heading);
    col.appendChild(list);
    coursesContainer.appendChild(col);
  });
}

// Contacts
const contactsNode = document.getElementById("contact-links");
profile.contacts.forEach((item) => {
  const anchor = document.createElement("a");
  anchor.className = "contact-chip";
  anchor.href = item.href;
  anchor.textContent = item.label;
  if (item.href.startsWith("http")) {
    anchor.target = "_blank";
    anchor.rel = "noreferrer";
  }
  contactsNode.appendChild(anchor);
});
